//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by eRepMapEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_RIBBON_BRIDGE               101
#define IDD_FORMVIEW                    101
#define IDS_RIBBON_PLAIN                102
#define IDS_RIBBON_WATER                103
#define IDS_RIBBON_HILL                 104
#define IDS_RIBBON_MOUNTAIN             105
#define IDS_STRING106                   106
#define IDS_RIBBON_FOREST               106
#define IDS_RIBBON_ELEMENTS             107
#define IDS_RIBBON_CURSOR               108
#define IDS_RIBBON_SIZE                 109
#define IDB_WRITESMALL                  110
#define IDS_RIBBON_WIDTH                110
#define IDB_WRITELARGE                  111
#define IDS_RIBBON_HEIGHT               111
#define IDB_MAIN                        112
#define IDS_STRING112                   112
#define IDS_RIBBON_RESIZE               112
#define IDB_BUTTONS                     113
#define IDS_RIBBON_BUILDINGS            113
#define IDB_FILELARGE                   114
#define IDS_RIBBON_SAVEAS_PICTURE       114
#define IDB_FILESMALL                   115
#define IDS_STRING115                   115
#define IDS_RIBBON_SCALE                115
#define IDS_RIBBON_ZOOMIN               116
#define IDS_STRING117                   117
#define IDS_RIBBON_ZOOMOUT              117
#define IDS_RIBBON_SCALES               118
#define IDR_POPUP_EDIT                  119
#define IDS_RIBBON_SHOW_NUMBERS         119
#define ID_STATUSBAR_PANE1              120
#define IDS_RIBBON_DEFENCES             120
#define ID_STATUSBAR_PANE2              121
#define IDS_RIBBON_HOSPITALS            121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_STRING124                   124
#define IDS_USERS_VIEW                  124
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_eRepMapEditorTYPE           130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_RIBBON_CAPTIONBAR           295
#define IDS_EDIT_MENU                   306
#define IDB_PNG1                        310
#define IDB_MAINTOOLBAR                 311
#define IDB_MAINTOOLBAR_SMALL           312
#define IDR_ELEMENTS_MENU               315
#define IDS_RIBBON_BIG_CITY             316
#define IDS_RIBBON_D1                   317
#define IDS_RIBBON_D2                   318
#define IDS_RIBBON_D3                   319
#define IDS_RIBBON_D4                   320
#define IDS_RIBBON_D5                   321
#define IDS_RIBBON_H1                   322
#define IDS_RIBBON_H2                   323
#define IDS_RIBBON_H3                   324
#define IDS_RIBBON_H4                   325
#define IDS_RIBBON_H5                   326
#define IDS_RIBBON_SMALL_CITY           327
#define IDC_ALL_MESSAGES_EDIT           1000
#define IDC_WRITE_MESSAGE_EDIT          1001
#define IDC_USERS_LIST                  1003
#define IDC_SEND_MESSAGE_BUTTON         1004
#define IDC_STATUS_STATIC               1005
#define IDC_MEMBERS_STATIC              1006
#define ID_H4                           32700
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_PLAIN                        32771
#define ID_BRIDGE                       32772
#define ID_WATER                        32773
#define ID_HILL                         32774
#define ID_ROCK                         32775
#define ID_FOREST                       32776
#define ID_MOUNTAIN                     32777
#define ID_CURSOR                       32778
#define ID_CURSOR_ELEMENT               32779
#define ID_WIDTH                        32780
#define ID_HEIGHT                       32781
#define ID_RESIZE_SIZE                  32782
#define ID_BRIDGE32783                  32783
#define ID_BRIDGE001001                 32784
#define ID_BRIDGE001010                 32785
#define ID_BRIDGE010001                 32786
#define ID_BRIDGE010010                 32787
#define ID_BRIDGE011000                 32788
#define ID_BRIDGE011011                 32789
#define ID_BRIDGE000011                 32790
#define ID_BRIDGE000101                 32791
#define ID_BRIDGE010100                 32792
#define ID_BRIDGE010101                 32793
#define ID_BRIDGE100010                 32794
#define ID_BRIDGE100100                 32795
#define ID_BRIDGE101000                 32796
#define ID_BRIDGE101010                 32797
#define ID_BRIDGE111111                 32798
#define ID_BIG_CITY                     32800
#define ID_D1                           32801
#define ID_D2                           32802
#define ID_D3                           32803
#define ID_D4                           32804
#define ID_D5                           32805
#define ID_H1                           32806
#define ID_H2                           32807
#define ID_H3                           32808
#define ID_H5                           32809
#define ID_SMALL_CITY                   32810
#define ID_FILE_SAVEASPICTURE           32811
#define ID_FILE_SAVE_AS_PICTURE         32812
#define ID_SCALE                        32813
#define ID_ZOOMIN_SCALE                 32814
#define ID_ZOOMOUT_SCALE                32815
#define ID_SHOWNUMBERS                  32816
#define ID_RIBBON_SHOW_NUMBERS          32817
#define ID_HOSPITALS                    32818
#define ID_DEFENCES                     32819
#define ID_SIMPLEBRIDGES                32820
#define ID_TURNINGBRIDGE                32821
#define ID_INTERCHANGEBRIDGES           32822
#define ID_VIEW_USERS                   32823
#define ID_CHAT_USERS                   32824
#define IDS_RIBBON_PAINT                61447

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        418
#define _APS_NEXT_COMMAND_VALUE         32825
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           328
#endif
#endif
